version: '3.9'
services:
    nats_1:
        image: 'nats:latest'
        command: '-js -n nats_1 --cluster nats://0.0.0.0:6222 --cluster_name ewf --routes nats://nats_1:6222 -m 8222'
        ports:
            - '4222:4222'
            - '8222:8222'
    nats_2:
        image: 'nats:latest'
        command: '-js -n nats_2 --cluster nats://0.0.0.0:6222 --cluster_name ewf --routes nats://nats_1:6222'
        depends_on:
            - 'nats_1'
        ports:
            - '4223:4222'
    nats_3:
        image: 'nats:latest'
        command: '-js -n nats_3 --cluster nats://0.0.0.0:6222 --cluster_name ewf --routes nats://nats_1:6222'
        ports:
            - '4224:4222'
        depends_on:
            - 'nats_1'

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
