name: Build and deploy test

on:
  push:
    branches: [ ddhub-test ]
    paths-ignore:
      - 'devops/**'

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  
  unique_id:
    runs-on: ubuntu-latest
    steps:
      - name: Generate unique id
        id: unique_id
        run: echo "::set-output name=id::$(uuidgen)"
    outputs:
      unique_id: ${{ steps.unique_id.outputs.id }}

  build_image:
    runs-on: ubuntu-latest
    needs: [unique_id]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Build packages and docker image
      run: |
        ./mvnw package -DskipTests
        docker build -f src/main/docker/Dockerfile.test-jvm -t energyweb/ddhub-messagebroker .
        
    - name: Login to Azure registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Push image (Azure)
      run: |
        docker tag energyweb/ddhub-messagebroker ${{ secrets.REGISTRY_LOGIN_SERVER }}/ddhub-messagebroker:test-${{needs.unique_id.outputs.unique_id}}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ddhub-messagebroker:test-${{needs.unique_id.outputs.unique_id}}
        docker tag energyweb/ddhub-messagebroker ${{ secrets.REGISTRY_LOGIN_SERVER }}/ddhub-messagebroker:test-canary
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ddhub-messagebroker:test-canary

    # - name: ArgoCD login
    #   uses: clowdhaus/argo-cd-action/@v1.8.0
    #   id: argocd_login
    #   with:
    #     command: login ${{ secrets.ARGOCD_DEV_URL }}
    #     options: --insecure --password ${{ secrets.ARGOCD_DEV_PASS }} --username ${{ secrets.ARGOCD_DEV_USERNAME }}

    # - name: ArgoCD overvrite values.yaml
    #   uses: clowdhaus/argo-cd-action/@v1.8.0
    #   id: argocd_image_tag_overwrite
    #   with:
    #     command: app set ddhub-messagebroker-dev
    #     options: -p ddhub-messagebroker.image.tag=test-${{needs.unique_id.outputs.unique_id}}
  