name: Build and deploy

on:
  push:
    branches: [ dev-workflow-no ]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  
  unique_id:
    runs-on: ubuntu-latest
    steps:
      - name: Generate unique id
        id: unique_id
        run: echo "::set-output name=id::$(uuidgen)"
    outputs:
      unique_id: ${{ steps.unique_id.outputs.id }}

  build_image:
    runs-on: ubuntu-latest
    needs: [unique_id]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Build packages
      run: ./mvnw package
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build & push docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        BUILD_ID: ${{needs.unique_id.outputs.unique_id}}
      run: |
        docker build -f src/main/docker/Dockerfile.jvm -t energyweb/ddhub-messagebroker:canary .
        docker tag energyweb/ddhub-messagebroker:canary $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:canary
        docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:canary
        docker tag $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:canary $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$BUILD_ID
        docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$BUILD_ID 
  