name: Pull Request

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'devops/**'
env:
  SECRETS_ENGINE: vault

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  build_and_test:
    runs-on: ubuntu-latest
    needs: [semantic-version]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Build packages and run test
      run: |
        ./mvnw package
